apiVersion: notification.toolkit.fluxcd.io/v1beta1	
kind: Provider	
metadata:	
  name: flux-system	
  namespace: flux-system	
spec:	
  type: github	
  address: https://github.com/coulof/arc-cicd-demo-gitops	
  secretRef:	
    name: github	
---	
apiVersion: notification.toolkit.fluxcd.io/v1beta1	
kind: Alert	
metadata:	
  name: arc-cicd-cluster	
  namespace: flux-system	
spec:	
  providerRef:	
    name: flux-system	
  eventSeverity: info	
  eventSources:	
    - kind: Kustomization	
      name: todos-todos	
      namespace: flux-system
---
apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: on-call-webapp
  namespace: flux-system
spec:
  providerRef:
    name: slack
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: '*'
    - kind: Kustomization
      name: '*'
