kind: Namespace
apiVersion: v1
metadata:
  name: todos-dev
---
kind: Namespace
apiVersion: v1
metadata:
  name: todos-prod
---
kind: Namespace
apiVersion: v1
metadata:
<<<<<<< Updated upstream
  name: todos-azure
=======
  name: todos-trial
>>>>>>> Stashed changes
